## This script sets up a signal bus used to communicate events between modules
## without having to manage if a module is loaded or not.
##
## Please do not add new signals before discussing on the WheelSims issue
## tracker, so that this signal bus stays clean.
extends Node

# Global signals generated by python_bridge

## Sent when Godot receives "ready" from Python. Each module that requires
## python_bridge should await SignalBus.python_bridge_connected in its
## _ready() function, to be sure that its commands will then be received by
## Python.
@warning_ignore("unused_signal")
signal python_bridge_connected

# signal pertaining to the current scene (main.gd)
@warning_ignore("unused_signal")
signal session_scene
@warning_ignore("unused_signal")
signal current_scene

# signal pertaining to player.gd, which saves (global_position, rotation)
@warning_ignore("unused_signal")
signal player_trajectory

# signal force_capture will be added later
